<!-- HTML fragment containing INSERT form for Suggested Events table (historysugg) -->
<p class="helptext">Fill out the form and submit to suggest an entry for History of the World.<br /><br />
Click on "Form Fields" below for info on each field.<br /><br />
After successful submittal new entry should appear under "Suggested Events" tab.</p>
   <p class="wc3xhtml1"><a class="wc3xhtml1" href="http://validator.w3.org/check?uri=referer"><img class="wc3xhtml1" src="http://www.w3.org/Icons/valid-xhtml10-blue" alt="Valid XHTML 1.0 Transitional" height="31" width="88" /></a></p>
   