<div id="timeline">
<div id="tl" class="timeline-default" style="height: 650px; border: 1px solid #aaa; font-size:10pt																																																																																																																																																																																																																																																																																																																																																																																																																																							"></div>
<div style="width: 100%">
	<table style="text-align: center; width: 100%">
        	<tr>
        	        <td><a href="javascript:centerTimeline(-11000);">11000 BC</a></td>
        	        <td><a href="javascript:centerTimeline(-8000);">8000 BC</a></td>
        	        <td><a href="javascript:centerTimeline(-6000);">6000 BC</a></td>
                	<td><a href="javascript:centerTimeline(-4000);">4000 BC</a></td>
        	        <td><a href="javascript:centerTimeline(-2000);">2000 BC</a></td>
        	        <td><a href="javascript:centerTimeline(-100);">100 BC</a></td>
        	        <td><a href="javascript:centerTimeline(2000);">2000 AD</a></td>
        	        <td><a href="javascript:centerTimeline(4000);">4000 AD</a></td>
        	        </tr>
        </table>
</div>
<div class="controls" id="controls">
    </div>
        <noscript>
        This page uses Javascript to show you a Timeline. Please enable Javascript in your browser to see the full page. Thank you.
        </noscript>
</div>
