<!-- HTML fragment containing instructions for Browse Events page -->
<div id="links">
<fieldset>
<legend>Links</legend>
<a href="http://www.clmitchell.net/home/main-contactus35/46-webmasters/1-calvin-mitchell.html" target="_blank">Contact Us for any Suggestions, Corrections or Feedback</a><br /><br />
<a href="https://github.com/Quasaur/History-of-the-World" target="_blank">History of the World on GitHub.com</a><br /><br />
<a href="http://www.clmitchell.net/" target="_blank">Calvin's Dot Net II</a><br /><br />
<a href="http://www.12x30.net/terms.html" target="_blank">Calendrical Terms</a><br /><br />
<a href="http://www.fourmilab.ch/cgi-bin/Solar" target="_blank">Solar System Live</a><br /><br />
<a href="http://www.bibletime.com/home/welcome/intro/bible-time-lines-and-theory-from-adam-to-the-present-including-prophetic" target="_blank">Bible Time</a><br /><br />
<a href="http://www.timehasanend.org" target="_blank">Time Has An End</a><br /><br />
<a href="http://www.nabataea.net/bstudents.html" target="_blank">Biblical Geography and Chronology</a><br /><br />
<a href="http://mapsofwar.com/ind/imperial-history.html" target="_blank">Maps of War</a><br /><br />
<a href="http://www.ancientworlds.net/" target="_blank">Ancient Worlds</a><br /><br />
<a href="http://www.hyperhistory.com/online_n2/History_n2/a.html" target="_blank">Hyperhistory Online</a><br /><br />
<a href="http://www.history.com/" target="_blank">The History Channel Online</a><br /><br />
<a href="http://www.friesian.com/notes/newking.htm" target="_blank">Ancient King Lists</a><br /><br />
<a href="http://www.wa-wd.com/" target="_blank">Who's Alive - Who's Dead</a><br /><br />
<a href="http://www.badley.info/history/" target="_blank">World History Database</a><br /><br />
<a href="http://www.computerhistory.org/timeline/" target="_blank">Timeline of Computer History</a><br /><br />
</fieldset>
</div>