<!-- HTML fragment containing Filter/Search form -->
<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="get" name="filters" id="filters" class="fstyle">
   <fieldset>
   <legend>Event Types</legend>
   <select name="selTypes" id="selTypes" tabindex="1">
   <option id="blank"></option>
   <option id="Astro">Astro</option>
   <option id="Biologic">Biologic</option>
   <option id="BirthDeath">Births-Deaths</option>
   <option id="Bloodline">Bloodline</option>
   <option id="Building">Building</option>
   <option id="Calendar">Calendar</option>
   <option id="City">City</option>
   <option id="Conversion">Conversion</option>
   <option id="Crown">Crown</option>
   <option id="Dearth">Dearth</option>
   <option id="Education">Education</option>
   <option id="Exploration">Exploration</option>
   <option id="Genocide">Genocide</option>
   <option id="Geo">Geo</option>
   <option id="Invention">Invention</option>
   <option id="Language">Language</option>
   <option id="Literature">Literature</option>
   <option id="Migration">Migration</option>
   <option id="Miracle">Miracle</option>
   <option id="Monument">Monument</option>
   <option id="Music">Music</option>
   <option id="Political">Political</option>
   <option id="Prophetic">Prophetic</option>
   <option id="Religion">Religion</option>
   <option id="Revelation">Revelation</option>
   <option id="Science">Science</option>
   <option id="Speech">Speech</option>
   <option id="Terrorism">Terrorism</option>
   <option id="War">War</option>
   </select>
   </fieldset>
   <fieldset>
   <legend>Event Location</legend>
   <select name="selNLL" id="selNLL" tabindex="2">
   <option id="blank1"></option>
   <option id="Africa">Africa</option>
   <option id="Americas">Americas</option>
   <option id="Arctic">Arctic (North)</option>
   <option id="Antarctic">Antarctic</option>
   <option id="Asia">Asia</option>
   <option id="Australia">Australia</option>
   <option id="Earth">Earth</option>
   <option id="Europe">Europe</option>
   <option id="Middle_East">Middle East</option>
   </select>
   </fieldset>
   <fieldset>
   <legend>Text Search</legend>
   <input class="fstyle" type="text" id="txtSearch" name="txtSearch" tabindex="3" />
   </fieldset><br />
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="btnSubmit" name="btnSubmit" class="fstyle" type="submit" value="Submit Request" tabindex="4" /><br />
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
   </form>
   <p class="wc3xhtml1"><a class="wc3xhtml1" href="http://validator.w3.org/check?uri=referer"><img class="wc3xhtml1" src="http://www.w3.org/Icons/valid-xhtml10-blue" alt="Valid XHTML 1.0 Transitional" height="31" width="88" /></a></p>
   