<!-- HTML fragment containing Collapsible Panel and Tab Menus
      used on every page -->
<noscript><h1>This page requires JavaScript. Please enable JavaScript in your browser and reload this page.</h1></noscript>
<h1 class="title">History of the World</h1>
<div id="tabsF"><!-- START tabsF Menu System -->
<ul>
<li><a href="index.php" title="Browse Events"><span>Browse</span></a></li>
<li><a href="add.php" title="Add Events"><span>Add</span></a></li>
<li><a href="map.php" title="Map Events"><span>Map</span></a></li>
<li><a href="cha.php" title="Chart Events"><span>Chart</span></a></li>
<li><a href="doc.php" title="Docs"><span>Learn</span></a></li>
<li><a href="clg.php" title="Change Log"><span>Changes</span></a></li>
<li><a href="lnk.php" title="Links"><span>Seek</span></a></li>
</ul>
</div><!-- END tabsF Menu System -->
