<!-- HTML fragment containing instructions for Browse/Suggested Events page -->
<p class="helptext"><strong>Event Type: New Type.</strong> Selecting the New Type radio input disables the Current List listbox and enables you to submit a New Event Type by typing in the text input field (located beneath the New Type radio input).</p>
<input id="btnHelp" name="btnHelp" type="button" value="Original Helptext" onclick="btnHndlr();" />
