<!-- HTML fragment containing instructions for Browse/Suggested Events page -->
<p class="helptext"><strong>Event: Description.</strong> Enter your Event Description in the text area provided.  You may use standard xhtml/ html formatting tags (please do not use div/layer tags...they will be removed).</p>
<p>Four items should be included in your Event Description:</p>
<ol>
   <li><b>A Detailed Location</b>, in bold.</li>
   <li><b>An Event Description</b> that includes the essential points.</li>
   <li><b>Date(s)</b> in the format 01-Jan-2008.</li>
   <li><b>A "Submitted by" Statement</b> with your Name, Email address (use '(at)' instead of '&#64;') or Nickname.</li>
</ol>
<input id="btnHelp" name="btnHelp" type="button" value="Original Helptext" onclick="btnHndlr();" />
