<!-- HTML fragment containing instructions for Browse/Suggested Events page -->
JavaScript must be enabled in browser<br /><br />
   Activate desired filters and Submit Request.<br /><br />
   Any combination of filters can be used.<br /><br />
   Searches are case-insensitive.<br /><br />
   Rows ending with a check are Anchor dates by which other events may be calculated.<br /><br />
   Records are constantly being moved from the Suggested Events table to the MAIN table (Browse Events). For this reason you will frequently receive an ERROR 1 (NO DATA WAS RETURNED) message.