<!-- HTML fragment containing instructions for Browse/Suggested Events page -->
JavaScript must be enabled in browser<br /><br />
   Activate desired filters and Submit Request.<br /><br />
   Any combination of filters can be used.<br /><br />
   Searches are case-insensitive.<br /><br />
   Rows ending with a check are Anchor dates by which other events may be calculated.<br /><br />
   <strong>ERRORS:</strong><br />
   <u><em>ERROR 1</em></u> (NO DATA WAS RETURNED) If you get this error without any filters being set, email me at calvin674(at)clmitchell.net. Otherwise, it means that there are no records that match the search filter you set.<br /></br>
   <u><em>ERROR 2</em></u> (COULD NOT CONNECT TO SERVER) The MySQL server is down; email me at calvin674(at)clmitchell.net.<br /></br>
   <u><em>ERROR 3</em></u> (COULD NOT SELECT DATABASE SERVER) The database on the MySQL server is unavailable; email me at calvin674(at)clmitchell.net.<br /></br>
   