<!-- HTML fragment containing instructions for Browse/Suggested Events page -->
<p class="helptext"><strong>Event Type: Current List (default).</strong> Selecting the Current List radio input enables you to select the Event Type from an existing list (located beneath the Current List radio input).</p>
<p class="helptext">As long as the Current List radio input is selected, the New Type text input field is disabled.</p>
<input id="btnHelp" name="btnHelp" type="button" value="Original Helptext" onclick="btnHndlr();" />
