<!-- HTML fragment containing instructions for Add Events page -->
<p class="helptext"><strong>Year: Bible.</strong> The Bible year is caculated based on an algorithm developed by <a href="http://www.bibletime.com/contact/?who=Phil%20Stone" target="_blank">Phil Stone</a>, who provides a tool that converts western Gregorian (New System [NS]) Years into Bible years. To use the tool, click on this <a href="http://www.bibletime.com/tool/time/gregorian/" target="_blank">link</a>.</p>
<input id="btnHelp" name="btnHelp" type="button" value="Original Helptext" onclick="btnHndlr();" />

   