<!-- HTML fragment containing instructions for Browse Events page -->
<fieldset>
<legend>Links</legend>
<a href="http://www.clmitchell.net/main-cit27/49-cat-cit-anthro/94-art-histworld.html" target="_blank">Changelog for This App</a><br />
<a href="http://www.clmitchell.net/" target="_blank">Calvin's Dot Net II</a><br />
<a href="http://www.12x30.net/terms.html" target="_blank">Calendrical Terms</a><br />
<a href="http://www.fourmilab.ch/cgi-bin/Solar" target="_blank">Solar System Live</a><br />
<a href="http://www.bibletime.com/home/index.html" target="_blank">Bible Time</a><br />
<a href="http://www.timehasanend.org" target="_blank">Time Has An End</a><br />
<a href="http://www.nabataea.net/bstudents.html" target="_blank">Biblical Geography and Chronology</a><br />
<a href="http://mapsofwar.com/ind/imperial-history.html" target="_blank">Maps of War</a><br />
<a href="http://www.ancientworlds.net/" target="_blank">Ancient Worlds</a><br />
<a href="http://www.hyperhistory.com/online_n2/History_n2/a.html" target="_blank">Hyperhistory Online</a><br />
<a href="http://www.history.com/" target="_blank">The History Channel Online</a><br />
<a href="http://www.friesian.com/notes/newking.htm" target="_blank">Ancient King Lists</a><br />
<a href="http://www.wa-wd.com/" target="_blank">Who's Alive - Who's Dead</a><br />
<a href="http://www.badley.info/history/" target="_blank">World History Database</a><br />
</fieldset>
